### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by srosh2000**
Added a readme for the docker repo documenting the steps I took to run R on AWS using this docker image template. Feel free to edit/cut out background steps if necessary.. hope this is helpful!

### CODE REVIEW

**Review by shrabasteebanerjee — CHANGES_REQUESTED** [review]
Hi Roshini, thanks a lot for this! One change: can you keep the docker-compose.yml file the same as what I had before, and only add the readme file in the pull request? you could just copy-paste my old docker-compose file to the repo, since you have the edited version saved?

**Comment by shrabasteebanerjee** [comment]
Actually I just manually copy pasted it so no worries :) thanks a lot!!

**Comment by srosh2000** [comment]
Perfect, no worries at all! 
Btw I wrote a building block on TSH which is more extensive.. Could be good to link it in the readme ? Here's the link: https://tilburgsciencehub.com/building-blocks/automate-and-execute-your-work/reproducible-work/rstudio-aws/

**Comment by srosh2000** [comment]
Perfect!
Btw I wrote a building block on TSH which is more extensive.. Could be good to link it in the readme ? Here's the link: https://tilburgsciencehub.com/building-blocks/automate-and-execute-your-work/reproducible-work/rstudio-aws/

**Pull request closed without merging**
